server:
  port: 8091

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**
        - id: experience-service
          uri: lb://experience-service
          predicates:
            - Path=/api/experience/**
      # default-filters:
      #   - JwtGlobalFilter

  webflux:
    cors:
      allowed-origin-patterns:
        - "*" # use allowedOriginPatterns instead of allowedOrigins
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
      max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    org.springframework.security: DEBUG
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
