# Global configuration for all services
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG



