# Application Service specific configuration
spring:
  application:
    name: application-service
  datasource:
    url: jdbc:mysql://localhost:3306/getemployed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Speaker@7654#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
