# Auth Service specific configuration
spring:
  application:
    name: sonyapigateway
  datasource:
    url: jdbc:mysql://localhost:3306/getemployed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # password: pass@word1
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

auth:
  interceptor:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
