# User Service specific configuration
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/getemployed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sppratham420
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
