spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getemployed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Speaker@7654#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

auth:
  interceptor:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security:
    enabled: false