spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getemployed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

